# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-13 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('total_employees', models.IntegerField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('recored_created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_created_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.Company')),
            ],
        ),
        migrations.CreateModel(
            name='JobOpenings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=150)),
                ('role_description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('record_created_date', models.DateTimeField(auto_now_add=True)),
                ('associated_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.Company')),
            ],
        ),
    ]
